<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="slideshow">

        <xs:complexType>

            <xs:sequence>

                <xs:element name="slide" maxOccurs="unbounded">

                    <xs:complexType>

                        <xs:sequence>

                            <xs:element name="title" type="xs:string" minOccurs="0"/>

                            <xs:element name="item" minOccurs="0" maxOccurs="unbounded">

                                <xs:complexType mixed="true">

                                    <xs:sequence>

                                        <xs:element name="em" type="xs:string" minOccurs="0"/>

                                    </xs:sequence>

                                </xs:complexType>

                            </xs:element>

                        </xs:sequence>

                        <xs:attribute name="type" type="xs:string" use="required"/>

                    </xs:complexType>

                </xs:element>

            </xs:sequence>

            <xs:attribute name="title" type="xs:string"/>
            <xs:attribute name="date" type="xs:string"/>
            <xs:attribute name="author" type="xs:string"/>

        </xs:complexType>

    </xs:element>

</xs:schema>